INSERT INTO
    hello_world (hello_name, email)
VALUES (
        'Hassan',
        'nazmulnb@gmail.com'
    )

-- Create students table
CREATE TABLE students (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    age INT,
    grade VARCHAR(2),
    course VARCHAR(100),
    email VARCHAR(100),
    dob DATE,
    blood_group VARCHAR(5),
    country VARCHAR(50)
);

-- Insert sample rows
INSERT INTO
    students (
        first_name,
        last_name,
        age,
        grade,
        course,
        email,
        dob,
        blood_group,
        country
    )
VALUES (
        'John',
        'Doe',
        20,
        'A',
        'Computer Science',
        'john.doe@example.com',
        '2005-03-15',
        'O+',
        'USA'
    ),
    (
        'Jane',
        'Smith',
        22,
        'B',
        'Mathematics',
        'jane.smith@example.com',
        '2003-07-22',
        'A+',
        'UK'
    ),
    (
        'Michael',
        'Johnson',
        19,
        'A',
        'Physics',
        'michael.johnson@example.com',
        '2006-11-05',
        'B+',
        'Canada'
    ),
    (
        'Emily',
        'Davis',
        21,
        'C',
        'Chemistry',
        NULL,
        '2004-02-18',
        'O-',
        'Australia'
    ),
    (
        'Daniel',
        'Martinez',
        23,
        'B',
        'Biology',
        'daniel.martinez@example.com',
        '2002-12-09',
        'AB+',
        'Mexico'
    ),
    (
        'Sophia',
        'Garcia',
        20,
        'A',
        'English Literature',
        'sophia.garcia@example.com',
        '2005-04-11',
        'A-',
        'Spain'
    ),
    (
        'James',
        'Wilson',
        24,
        'C',
        'History',
        'james.wilson@example.com',
        '2001-08-30',
        'B-',
        'USA'
    ),
    (
        'Olivia',
        'Anderson',
        18,
        'B',
        'Economics',
        'olivia.anderson@example.com',
        '2007-01-25',
        'O+',
        'UK'
    ),
    (
        'Ethan',
        'Thomas',
        21,
        'A',
        'Philosophy',
        'ethan.thomas@example.com',
        '2004-05-19',
        'A+',
        'Germany'
    ),
    (
        'Isabella',
        'Taylor',
        22,
        'C',
        'Sociology',
        'isabella.taylor@example.com',
        '2003-09-13',
        'AB-',
        'France'
    ),
    (
        'Alexander',
        'Moore',
        19,
        'B',
        'Political Science',
        'alex.moore@example.com',
        '2006-06-07',
        'O-',
        'USA'
    ),
    (
        'Mia',
        'Jackson',
        20,
        'A',
        'Computer Engineering',
        'mia.jackson@example.com',
        '2005-02-28',
        'B+',
        'India'
    ),
    (
        'William',
        'White',
        23,
        'C',
        'Psychology',
        'william.white@example.com',
        '2002-04-17',
        'O+',
        'Canada'
    ),
    (
        'Ava',
        'Harris',
        21,
        'B',
        'Fine Arts',
        'ava.harris@example.com',
        '2004-12-21',
        'A-',
        'Australia'
    ),
    (
        'Benjamin',
        'Martin',
        22,
        'A',
        'Business Administration',
        'benjamin.martin@example.com',
        '2003-03-03',
        'B-',
        'USA'
    ),
    (
        'Charlotte',
        'Thompson',
        19,
        'C',
        'Nursing',
        'charlotte.thompson@example.com',
        '2006-07-10',
        'O+',
        'UK'
    ),
    (
        'Lucas',
        'Martins',
        20,
        'B',
        'Engineering',
        'lucas.martins@example.com',
        '2005-10-29',
        'AB+',
        'Brazil'
    ),
    (
        'Amelia',
        'Lopez',
        24,
        'A',
        'Architecture',
        'amelia.lopez@example.com',
        '2001-01-06',
        'O-',
        'Mexico'
    ),
    (
        'Henry',
        'Clark',
        23,
        'B',
        'Law',
        'henry.clark@example.com',
        '2002-05-25',
        'A+',
        'USA'
    ),
    (
        'Evelyn',
        'Lewis',
        18,
        'A',
        'Media Studies',
        'evelyn.lewis@example.com',
        '2007-09-14',
        'B+',
        'UK'
    ),
    (
        'Jack',
        'Walker',
        22,
        'C',
        'Statistics',
        'jack.walker@example.com',
        '2003-11-30',
        'AB-',
        'Germany'
    ),
    (
        'Harper',
        'Allen',
        21,
        'B',
        'Medicine',
        'harper.allen@example.com',
        '2004-08-08',
        'O+',
        'Canada'
    ),
    (
        'Sebastian',
        'Young',
        20,
        'A',
        'Astronomy',
        'sebastian.young@example.com',
        '2005-06-12',
        'B-',
        'Australia'
    ),
    (
        'Ella',
        'King',
        19,
        'B',
        'Anthropology',
        'ella.king@example.com',
        '2006-12-20',
        'A-',
        'France'
    ),
    (
        'Matthew',
        'Scott',
        23,
        'C',
        'Linguistics',
        'matthew.scott@example.com',
        '2002-03-09',
        'O+',
        'USA'
    ),
    (
        'Abigail',
        'Adams',
        22,
        'A',
        'Music',
        'abigail.adams@example.com',
        '2003-07-27',
        'B+',
        'UK'
    ),
    (
        'Joseph',
        'Baker',
        21,
        'B',
        'Drama',
        'joseph.baker@example.com',
        '2004-10-18',
        'O-',
        'USA'
    ),
    (
        'Emily',
        'Rodriguez',
        20,
        'C',
        'Fashion Design',
        'emily.rodriguez@example.com',
        '2005-01-23',
        'AB+',
        'Spain'
    ),
    (
        'David',
        'Perez',
        19,
        'A',
        'Graphic Design',
        'david.perez@example.com',
        '2006-04-02',
        'O+',
        'Mexico'
    ),
    (
        'Lily',
        'Carter',
        24,
        'B',
        'Journalism',
        'lily.carter@example.com',
        '2001-09-11',
        'A-',
        'USA'
    ),
    (
        'Samuel',
        'Mitchell',
        22,
        'C',
        'Geography',
        'samuel.mitchell@example.com',
        '2003-12-06',
        'O+',
        'UK'
    ),
    (
        'Grace',
        'Evans',
        23,
        'B',
        'Education',
        'grace.evans@example.com',
        '2002-05-14',
        'B+',
        'Canada'
    ),
    (
        'Andrew',
        'Turner',
        21,
        'A',
        'Sports Science',
        'andrew.turner@example.com',
        '2004-11-22',
        'AB-',
        'Germany'
    );